AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Passos Magicos — Infraestrutura: IAM Role para SageMaker, SageMaker Model, EndpointConfig e Endpoint.

Parameters:
  ImageTag:
    Type: String
    Description: Tag da imagem Docker (github.sha)
  GitHubSha:
    Type: String
    Description: Tag da imagem Docker (github.sha)

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: Ambiente de deploy

Resources:

  # --------------------------------------------------------------------------
  # 1. IAM Role
  # --------------------------------------------------------------------------
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMakerExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Policies:
        - PolicyName: SageMakerCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/sagemaker/*

  # --------------------------------------------------------------------------
  # 2. SageMaker Model
  # --------------------------------------------------------------------------
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Sub "passos-magicos"
      # ModelName: !Sub "passos-magicos-${Environment}-${GitHubSha}"
      PrimaryContainer:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/passos-magicos:${ImageTag}
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn

  # --------------------------------------------------------------------------
  # 3. SageMaker EndpointConfig
  # --------------------------------------------------------------------------
  SageMakerEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      EndpointConfigName: !Sub passos-magicos-${Environment}-${GitHubSha}
      ProductionVariants:
        - VariantName: AllTraffic
          ModelName: !Ref SageMakerModel
          ServerlessConfig:
            MemorySizeInMB: 2048
            MaxConcurrency: 10

  # --------------------------------------------------------------------------
  # 4. SageMaker Endpoint 
  # --------------------------------------------------------------------------
  SageMakerEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Sub passos-magicos-${Environment}
      EndpointConfigName: !GetAtt SageMakerEndpointConfig.EndpointConfigName

# ── Outputs ───────────────────────────────────────────────────────────────────
Outputs:
  SageMakerExecutionRoleArn:
    Description: ARN da role do SageMaker
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SageMakerExecutionRoleArn

  SageMakerEndpointName:
    Description: Nome do endpoint SageMaker
    Value: !GetAtt SageMakerEndpoint.EndpointName
    Export:
      Name: !Sub ${AWS::StackName}-SageMakerEndpointName

  ECRImageUri:
    Description: URI da imagem utilizada neste deploy
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/passos-magicos:${ImageTag}